[package]
name = "hGB-client"
license = "MIT OR Apache-2.0"
edition.workspace = true
version.workspace = true

[dependencies]
hGB-proto = { path = "../hGB-proto" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
uuid = { version = "1", features = ["serde", "v4"] }
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.8"
anyhow = "1"
hex = "0.4"


